/**
 * Graph Compiler — 图转 Python 脚本引擎
 */

import {
  type SerializedGraph,
  type SerializedNode,
  type SerializedEdge,
} from "./types";
import { NODE_REGISTRY } from "./node-registry";

// ─── Topological Sort ────────────────────────────────────

interface SortResult {
  order: string[];
  hasCycle: boolean;
}

export function topologicalSort(nodes: SerializedNode[], edges: SerializedEdge[]): SortResult {
  const nodeIds = new Set(nodes.map(n => n.id));
  const inDegree = new Map<string, number>();
  const adjacency = new Map<string, string[]>();

  for (const id of nodeIds) {
    inDegree.set(id, 0);
    adjacency.set(id, []);
  }

  for (const edge of edges) {
    if (nodeIds.has(edge.source) && nodeIds.has(edge.target)) {
      adjacency.get(edge.source)!.push(edge.target);
      inDegree.set(edge.target, (inDegree.get(edge.target) ?? 0) + 1);
    }
  }

  const queue: string[] = [];
  for (const [id, deg] of inDegree) {
    if (deg === 0) queue.push(id);
  }

  const order: string[] = [];
  while (queue.length > 0) {
    const current = queue.shift()!;
    order.push(current);

    for (const neighbor of adjacency.get(current) ?? []) {
      const newDeg = (inDegree.get(neighbor) ?? 1) - 1;
      inDegree.set(neighbor, newDeg);
      if (newDeg === 0) queue.push(neighbor);
    }
  }

  return {
    order,
    hasCycle: order.length !== nodeIds.size,
  };
}

// ─── Variable Name Utils ─────────────────────────────────

function sanitize(id: string): string {
  return id.replace(/[^a-zA-Z0-9_]/g, "_");
}

function varName(nodeId: string, portId: string): string {
  return `${sanitize(nodeId)}__${sanitize(portId)}`;
}

function instanceName(nodeId: string): string {
  return `_node_${sanitize(nodeId)}`;
}

// ─── Code Generator ──────────────────────────────────────

export interface CompileResult {
  success: boolean;
  script: string;
  errors: string[];
  warnings: string[];
  executionOrder: string[];
}

export function compileGraph(graph: SerializedGraph): CompileResult {
  const errors: string[] = [];
  const warnings: string[] = [];

  const { order, hasCycle } = topologicalSort(graph.nodes, graph.edges);
  if (hasCycle) {
    errors.push("图中存在循环依赖，无法编译为线性脚本。请检查连线。");
    return { success: false, script: "", errors, warnings, executionOrder: [] };
  }

  const inputMapping = new Map<string, { sourceNode: string; sourcePort: string }>();
  for (const edge of graph.edges) {
    const key = `${edge.target}::${edge.targetPort}`;
    inputMapping.set(key, { sourceNode: edge.source, sourcePort: edge.sourcePort });
  }

  const imports = new Set<string>();
  const nodeMap = new Map(graph.nodes.map(n => [n.id, n]));

  for (const nodeId of order) {
    const node = nodeMap.get(nodeId);
    if (!node) continue;
    const def = NODE_REGISTRY.get(node.definitionType);
    if (!def) {
      errors.push(`未知节点类型: ${node.definitionType} (节点: ${nodeId})`);
      continue;
    }
    imports.add(`from ${def.pythonModule} import ${def.pythonClass}`);
  }

  if (errors.length > 0) {
    return { success: false, script: "", errors, warnings, executionOrder: order };
  }

  const lines: string[] = [];

  lines.push(`# === Auto-generated by AI Workflow Orchestrator ===`);
  lines.push(`# Graph: ${graph.name}`);
  lines.push(`# Version: ${graph.version}`);
  lines.push(`# Generated: ${new Date().toISOString()}`);
  lines.push(`# Execution order: ${order.join(" → ")}`);
  lines.push(`#`);
  lines.push(`# DO NOT EDIT — 此脚本由图自动生成`);
  lines.push(``);

  lines.push(`import json`);
  lines.push(`import sys`);
  lines.push(`import os`);
  lines.push(`import time`);
  lines.push(``);
  for (const imp of imports) {
    lines.push(imp);
  }
  lines.push(``);

  lines.push(`# ─── Progress Reporting Protocol ─────────────────────`);
  lines.push(``);
  lines.push(`def _report(type_: str, node_id: str, **kwargs):`);
  lines.push(`    payload = {"type": type_, "node_id": node_id, "timestamp": time.time(), **kwargs}`);
  lines.push(`    print(json.dumps(payload, ensure_ascii=False), flush=True)`);
  lines.push(``);
  lines.push(`def report_progress(node_id: str, progress: float, message: str = ""):`);
  lines.push(`    _report("progress", node_id, progress=progress, message=message)`);
  lines.push(``);
  lines.push(`def report_status(node_id: str, status: str, message: str = ""):`);
  lines.push(`    _report("status", node_id, status=status, message=message)`);
  lines.push(``);
  lines.push(`def report_metrics(node_id: str, metrics: dict):`);
  lines.push(`    _report("metrics", node_id, metrics=metrics)`);
  lines.push(``);
  lines.push(`def report_error(node_id: str, error: str):`);
  lines.push(`    _report("error", node_id, error=error)`);
  lines.push(``);

  lines.push(`# ─── Pipeline Execution ──────────────────────────────`);
  lines.push(``);
  lines.push(`def main():`);
  lines.push(`    pipeline_start = time.time()`);
  lines.push(`    _report("status", "__pipeline__", status="running", message="Pipeline started")`);
  lines.push(``);

  for (const nodeId of order) {
    const node = nodeMap.get(nodeId)!;
    const def = NODE_REGISTRY.get(node.definitionType)!;
    const inst = instanceName(nodeId);

    lines.push(`    # ─── Node: ${nodeId} (${def.pythonClass}) ───`);
    lines.push(`    report_status("${nodeId}", "running")`);
    lines.push(`    try:`);

    const paramStr = JSON.stringify(node.paramValues, null, 8);
    lines.push(`        ${inst} = ${def.pythonClass}(params=${paramStr.replace(/\n/g, "\n        ")})`);

    const execArgs: string[] = [];
    for (const inputPort of def.inputs) {
      const key = `${nodeId}::${inputPort.id}`;
      const mapping = inputMapping.get(key);
      if (mapping) {
        execArgs.push(`${inputPort.id}=${varName(mapping.sourceNode, mapping.sourcePort)}`);
      } else if (inputPort.required) {
        warnings.push(`节点 ${nodeId} 的必须输入端口 "${inputPort.id}" 未连接`);
        execArgs.push(`${inputPort.id}=None  # WARNING: 必须端口未连接!`);
      }
    }

    execArgs.push(`progress_callback=lambda p, m="": report_progress("${nodeId}", p, m)`);

    if (def.outputs.length === 0) {
      lines.push(`        ${inst}.execute(`);
      for (const arg of execArgs) {
        lines.push(`            ${arg},`);
      }
      lines.push(`        )`);
    } else if (def.outputs.length === 1) {
      const outVar = varName(nodeId, def.outputs[0].id);
      lines.push(`        ${outVar} = ${inst}.execute(`);
      for (const arg of execArgs) {
        lines.push(`            ${arg},`);
      }
      lines.push(`        )`);
    } else {
      const resultVar = `${inst}_result`;
      lines.push(`        ${resultVar} = ${inst}.execute(`);
      for (const arg of execArgs) {
        lines.push(`            ${arg},`);
      }
      lines.push(`        )`);

      for (const outPort of def.outputs) {
        const outVar = varName(nodeId, outPort.id);
        lines.push(`        ${outVar} = ${resultVar}.get("${outPort.id}")`);
      }
    }

    if (def.builtinEvaluate && node.paramValues["builtin_evaluate"]) {
      lines.push(`        # 内置评估`);
      lines.push(`        if hasattr(${inst}, "evaluate"):`);
      lines.push(`            _eval_metrics = ${inst}.evaluate()`);
      lines.push(`            report_metrics("${nodeId}", _eval_metrics)`);
    }

    lines.push(`        report_status("${nodeId}", "success")`);

    lines.push(`    except Exception as e:`);
    lines.push(`        report_error("${nodeId}", str(e))`);
    lines.push(`        report_status("${nodeId}", "error", message=str(e))`);
    lines.push(`        raise  # 中断流水线`);
    lines.push(``);
  }

  lines.push(`    elapsed = time.time() - pipeline_start`);
  lines.push(`    _report("status", "__pipeline__", status="success", message=f"Pipeline complete in {elapsed:.1f}s")`);
  lines.push(``);
  lines.push(``);
  lines.push(`if __name__ == "__main__":`);
  lines.push(`    try:`);
  lines.push(`        main()`);
  lines.push(`    except Exception as e:`);
  lines.push(`        _report("status", "__pipeline__", status="error", message=str(e))`);
  lines.push(`        sys.exit(1)`);

  return {
    success: errors.length === 0,
    script: lines.join("\n"),
    errors,
    warnings,
    executionOrder: order,
  };
}

// ─── Graph Validation ────────────────────────────────────

export interface ValidationResult {
  valid: boolean;
  errors: string[];
  warnings: string[];
}

export function validateGraph(graph: SerializedGraph): ValidationResult {
  const errors: string[] = [];
  const warnings: string[] = [];
  const nodeMap = new Map(graph.nodes.map(n => [n.id, n]));

  for (const node of graph.nodes) {
    if (!NODE_REGISTRY.has(node.definitionType)) {
      errors.push(`节点 "${node.id}" 的类型 "${node.definitionType}" 未在注册表中`);
    }
  }

  if (graph.nodes.length === 0) {
    errors.push("图是空的，没有任何节点");
    return { valid: false, errors, warnings };
  }

  const connectedInputs = new Set<string>();
  for (const edge of graph.edges) {
    connectedInputs.add(`${edge.target}::${edge.targetPort}`);
  }

  for (const node of graph.nodes) {
    const def = NODE_REGISTRY.get(node.definitionType);
    if (!def) continue;

    for (const input of def.inputs) {
      if (input.required && !connectedInputs.has(`${node.id}::${input.id}`)) {
        warnings.push(`节点 "${node.id}" 的必须输入端口 "${input.label}" 未连接`);
      }
    }
  }

  const { hasCycle } = topologicalSort(graph.nodes, graph.edges);
  if (hasCycle) {
    errors.push("图中存在循环依赖");
  }

  const connectedNodes = new Set<string>();
  for (const edge of graph.edges) {
    connectedNodes.add(edge.source);
    connectedNodes.add(edge.target);
  }
  for (const node of graph.nodes) {
    if (!connectedNodes.has(node.id) && graph.nodes.length > 1) {
      warnings.push(`节点 "${node.id}" 是孤立的（未连接任何边）`);
    }
  }

  for (const edge of graph.edges) {
    if (!nodeMap.has(edge.source)) {
      errors.push(`边 "${edge.id}" 引用了不存在的源节点: ${edge.source}`);
    }
    if (!nodeMap.has(edge.target)) {
      errors.push(`边 "${edge.id}" 引用了不存在的目标节点: ${edge.target}`);
    }
  }

  return {
    valid: errors.length === 0,
    errors,
    warnings,
  };
}

// ─── Serialization helpers ───────────────────────────────

export function solidFlowToSerializedGraph(
  flowObject: { nodes: any[]; edges: any[] },
  name: string = "untitled",
): SerializedGraph {
  const nodes: SerializedNode[] = flowObject.nodes.map(n => ({
    id: n.id,
    definitionType: n.data?.definitionType ?? n.type ?? "unknown",
    paramValues: n.data?.paramValues ?? {},
    inputPortIds: n.data?.inputPortIds ?? [],
    outputPortIds: n.data?.outputPortIds ?? [],
    position: n.position ?? { x: 0, y: 0 },
  }));

  const edges: SerializedEdge[] = flowObject.edges.map((e: any) => ({
    id: e.id,
    source: e.source,
    sourcePort: e.sourceHandle ?? "output",
    target: e.target,
    targetPort: e.targetHandle ?? "input",
  }));

  return {
    version: "1.0.0",
    name,
    nodes,
    edges,
  };
}
